app/urls.py
from django.urls import path

from .views import SpotListView, CoordsEditor

app_name = "app"

urlpatterns = [
    path('spot-list/', SpotListView.as_view(), name='spot-list'),
    path('edit-coords/<int:pk>', CoordsEditor.as_view(), name='edit-coords'),
]

edit_dialog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='app:spot-list')),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/models.py
import json

from django.db import models


class Spot(models.Model):
    '''地図上のスポットのデータ
    '''
    name = models.CharField('名前', max_length=100)
    coords = models.JSONField('座標', default=dict)

    def __str__(self):
        return self.name

    def coords_str(self):
        '''座標を JSON 文字列で返す
        '''
        return json.dumps(self.coords, indent=4)

    def gmap_url(self):
        '''Google Maps のその座標の URL を返す
        '''
        coords = f'{self.coords["latitude"]}%2C{self.coords["longitude"]}'
        return 'https://www.google.com/maps/search/?api=1&query=' + coords

app/forms.py
from django import forms


class CoordsForm(forms.Form):
    latitude = forms.FloatField(label='緯度', min_value=-90.0, max_value=90.0)
    longitude = forms.FloatField(label='経度', min_value=-180.0, max_value=180.0)

app/views.py
from urllib.parse import urlparse

from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.views.generic.edit import FormView

from .forms import CoordsForm
from .models import Spot


class SpotListView(ListView):
    '''スポット一覧画面
    '''
    model = Spot
    template_name = 'app/spot_list.html'


class CoordsEditor(FormView):
    '''座標編集画面
    '''
    template_name = 'app/coords_edit.html'
    form_class = CoordsForm

    def get_object(self):
        '''編集対象のスポットを取得する
        '''
        if not hasattr(self, 'object'):
            id = self.kwargs.get('pk')
            self.object = get_object_or_404(Spot, id=id)
        return self.object

    def get_initial(self):
        '''フォームに与える初期値を取得する
        '''
        spot = self.get_object()
        return {
            'latitude': spot.coords['latitude'],
            'longitude': spot.coords['longitude'],
        }

    def get_context_data(self, **kwargs):
        '''テンプレートに渡すデータを取得する
        '''
        context = super().get_context_data(**kwargs)

        # 編集の対象となるスポットの id と name
        spot = self.get_object()
        context['spot_id'] = spot.pk        # URL 生成や呼び出し元の判定用
        context['spot_name'] = spot.name    # スポット名の表示用

        # GET パラメタを参照できるようにする
        context['success'] = self.request.GET.get('success')  # 保存成功後か
        context['close'] = self.request.GET.get('close')      # 閉じるか

        # メッセージ配信で指定するためのオリジン
        referer = self.request.META.get('HTTP_REFERER', '')
        if referer:
            parsed_url = urlparse(referer)
            origin = parsed_url.scheme + "://" + parsed_url.netloc
            context['origin'] = origin

        return context

    def get_success_url(self) -> str:
        # POST 処理が正常終了したら、GET パラメタを付けて同じページを再表示する
        url = self.request.path + '?success=1'

        # 「保存して閉じる」(close=1) だったら閉じるための GET パラメタを付ける
        close = self.request.GET.get('close')
        if (close):
            url += '&close=1'

        return url

    def form_valid(self, form):
        spot = self.get_object()
        spot.coords = {
            'latitude': form.cleaned_data['latitude'],
            'longitude': form.cleaned_data['longitude']
        }
        spot.save()
        return super().form_valid(form)

app/templates/app/coords_edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Coords Edit</title>
</head>
<body>

<h1>{{ spot_name }} の座標</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
</form>

<button onclick="window.close();">閉じる</button>
<button onclick="revert();">編集前に戻す</button>
<button onclick="save(false);">保存して編集を続ける</button>
<button onclick="save(true);">保存して閉じる</button>

{# 「保存して編集を続ける / 保存して閉じる」が成功してリダイレクトして来た場合 #}
{% if success and origin %}
<script>
  // 呼び出し元のウィンドウに、座標の情報を送信する
  const coords = {
    latitude: {{ form.latitude.value }},
    longitude: {{ form.longitude.value }}
  };
  const message = {
    spotId: "{{ spot_id }}",
    coords: JSON.stringify(coords, null, '    ')
  };
  window.opener.postMessage(message, "{{ origin }}");
</script>
{% endif %}

{# 「保存して閉じる」が成功してリダイレクトして来た場合 #}
{% if success and close %}
<script>
  window.close();
</script>
{% endif %}

<script>
  // form を送信する関数
  function save(close) {
    const form = document.forms[0];
    let url = "{% url 'app:edit-coords' spot_id %}";

    // 保存して閉じるなら、閉じるフラグを GET パラメタにセットする
    if (close) {
      url += "?close=1";
    }

    form.action = url;
    form.submit();
  }

  // 編集前に戻す関数
  function revert() {
    const url = "{% url 'app:edit-coords' spot_id %}";
    location.replace(url);
  }
</script>

</body>
</html>

app/templates/app/spot_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Spot List</title>
  <style>
    td {
      padding: 0 1em;
    }
  </style>
</head>
<body>
  <h1>Spot List</h1>
  <table rules="rows">
    <tr><th>スポット</th><th>座標</th></tr>
    {% for spot in object_list %}
      <tr>
        <td>
          <a id="link_{{ spot.id }}" href="{{ spot.gmap_url }}" target="_blank">{{ spot.name }}</a>
        </td>
        <td>
          <pre id="coords_{{ spot.id }}">{{ spot.coords_str }}</pre>
        </td>
        <td>
          <a href="javascript:void(0);" onclick="openEditDialog(event);" spotId="{{ spot.id }}">編集</a>
        </td>
      </tr>
    {% endfor %}
  </table>

  <script>
    // 開いたダイアログを憶えておく連想配列
    const dialogs = {};

    // 座標編集用のダイアログを開く
    function openEditDialog(event) {
      // クリックされた要素からスポットの id を取得して URL を作る
      const spotId = event.target.attributes.spotId.value;
      const url = `/app/edit-coords/${spotId}`;

      // 座標編集画面をダイアログとして開く
      const coordsEditor = window.open(url, `coords_${spotId}`, "popup, width=600, height=400");

      // 開いたダイアログを dialogs に登録する (すでに開いていれば上書きする)
      dialogs[spotId] = coordsEditor;
    }

    // 座標の JSON から Google Maps のその座標の URL を作る
    function getGMapUrl(coords) {
      const coords_obj = JSON.parse(coords);
      const query = `${coords_obj.latitude}%2C${coords_obj.longitude}`;
      return 'https://www.google.com/maps/search/?api=1&query=' + query;
    }

    // dialog からのメッセージを受け取るようにする
    window.addEventListener('message', e => {
      // dialogs に登録された Window からのメッセージのみ処理する
      const spotId = e.data.spotId;
      if (dialogs[spotId] === e.source) {
        // 表示中の座標の値を更新する
        const coordsPre = document.getElementById(`coords_${e.data.spotId}`);
        coordsPre.innerText = e.data.coords

        // Google Maps へのリンクを更新する
        const link = document.getElementById(`link_${e.data.spotId}`);
        link.setAttribute('href', getGMapUrl(e.data.coords));
      }
    });

    // このページを離れたら開いたダイアログも閉じるようにする
    window.addEventListener('beforeunload', e => {
      for (let key in dialogs) {
        dialogs[key].close();
      }
    });
  </script>
</body>
</html>